#!/bin/sh /etc/rc.common
### BEGIN INIT INFO
# Provides:          batman_init
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     S
# Default-Stop:
# Short-Description: BATMAN initialisation.
# Description:       BATMAN initialisation.
### END INIT INFO

START=40

USE_PROCD=1

aggregated() {
    VAL=`uci get batman-adv.bat0.aggregated_ogms`
    if [ $VAL == '0' ]; then
        echo disabled > /sys/class/net/bat0/mesh/aggregated_ogms
        return 0
    fi
    echo enabled > /sys/class/net/bat0/mesh/aggregated_ogms
}

ap_isolation() {
    VAL=`uci get batman-adv.bat0.ap_isolation`
    if [ $VAL == '0' ]; then
        echo disabled > /sys/class/net/bat0/mesh/ap_isolation
        return 0
    fi
    echo enabled > sys/class/net/bat0/mesh/ap_isolation
}

bonding() {
    VAL=`uci get batman-adv.bat0.bonding`
    if [ $VAL == '0' ]; then
        echo disabled > /sys/class/net/bat0/mesh/bonding
        return 0
    fi
    echo enabled > /sys/class/net/bat0/mesh/bonding
}

bridge_loop_avoidance() {
    VAL=`uci get batman-adv.bat0.bridge_loop_avoidance`
    if [ $VAL == '0' ]; then
        echo disabled > /sys/class/net/bat0/mesh/bridge_loop_avoidance 
        return 0
    fi
    echo enabled > /sys/class/net/bat0/mesh/bridge_loop_avoidance 
}

fragmentation() {
    VAL=`uci get batman-adv.bat0.fragmentation`
    if [ $VAL == '0' ]; then
        echo disabled > /sys/class/net/bat0/mesh/fragmentation 
        return 0
    fi
    echo enabled > /sys/class/net/bat0/mesh/fragmentation 
}

gw_bandwidth() {
    VAL=`uci get batman-adv.bat0.gw_bandwidth`
    echo $VAL > /sys/class/net/bat0/mesh/gw_bandwidth
}

gw_mode() {
    VAL=`uci get batman-adv.bat0.gw_mode`
    echo $VAL > /sys/class/net/bat0/mesh/gw_mode
}

gw_sel_class() {
    VAL=`uci get batman-adv.bat0.gw_sel_class`
    echo $VAL > /sys/class/net/bat0/mesh/gw_sel_class
}

hop_penalty() {
    VAL=`uci get batman-adv.bat0.hop_penalty`
    echo $VAL > /sys/class/net/bat0/mesh/hop_penalty
}

isolation_mark() {
    VAL=`uci get batman-adv.bat0.isolation_mark`
    echo $VAL > /sys/class/net/bat0/mesh/isolation_mark
}

org_interval() {
    VAL=`uci get batman-adv.bat0.orig_interval`
    echo $VAL > /sys/class/net/bat0/mesh/orig_interval
}

routing_algo() {
    VAL=`uci get batman-adv.bat0.routing_algo`
    echo $VAL > /sys/module/batman_adv/parameters/routing_algo
}

init() {
    IP=`uci get batman-adv.bat0.ip`
    MASK=`uci get batman-adv.bat0.mask`
    ifconfig bat0 $IP netmask $MASK
    aggregated
    bonding
    bridge_loop_avoidance
    fragmentation
    gw_bandwidth
    gw_mode
    gw_sel_class
    hop_penalty
    isolation_mark
    org_interval
    ap_isolation
}

start_service() {
    ENABLE=`uci get batman-adv.bat0.enable`
    if [ $ENABLE == '0' ]; then 
        echo "Batman-adv is set to disabled"
        return 0
    fi
    routing_algo
    INTERFACE=`uci get batman-adv.bat0.mesh_iface`
    while true; do
        sleep 2
        if ifconfig $INTERFACE | grep inet; then break
        fi
    done
    echo bat0 > /sys/class/net/$INTERFACE/batman_adv/mesh_iface
    sleep 2
    init
	/usr/local/bin/batman_monitor.sh &
}

stop_service() {
	killall batman_monitor.sh
    INTERFACE=`uci get batman-adv.bat0.mesh_iface`
    echo none > /sys/class/net/$INTERFACE/batman_adv/mesh_iface
}

restart() {
    stop_service
    routing_algo
    INTERFACE=`uci get batman-adv.bat0.mesh_iface`
    echo bat0 > /sys/class/net/$INTERFACE/batman_adv/mesh_iface
    sleep 2
    init
	/usr/local/bin/batman_monitor.sh &
}

