#!/bin/sh /etc/rc.common
# chkconfig: S 10 10
# description: Configuration setup from database
#
### BEGIN INIT INFO
# Provides:          btinit
# Required-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description:
# Description:
#

START=18
USE_PROCD=1

### END INIT INFO
# Function that starts the daemon/service
#

CURRENT_PRTCL=1

start_service() 
{
	echo Starting snmpd....
	snmpd
}

stop_service()
{
	echo Stopping snmpd
	killall snmpd
}

